//! ffprobe 7.1.3 参数规格表.
//!
//! 说明:
//! - `MAIN_OPTIONS` 覆盖 `ffprobe -h` 的主参数接口.
//! - `AVOPTION_NAMES` 覆盖 AVOptions 名称接口, 用于“参数可识别”阶段.

/// 参数值类型.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OptionValueKind {
    /// 不接受值.
    None,
    /// 必须携带值.
    Required,
    /// 值可选.
    Optional,
}

/// 单个参数规格.
#[derive(Debug, Clone, Copy)]
pub struct OptionSpec {
    /// 规范名.
    pub canonical: &'static str,
    /// 别名列表（不含前导短横线）.
    pub aliases: &'static [&'static str],
    /// 参数值规则.
    pub value_kind: OptionValueKind,
}

impl OptionSpec {
    /// 判断给定别名是否命中当前规格.
    pub fn matches(&self, alias: &str) -> bool {
        self.aliases.contains(&alias)
    }
}

/// ffprobe 7.1.3 主参数接口（来自 `ffprobe -h`）.
pub const MAIN_OPTIONS: &[OptionSpec] = &[
    OptionSpec {
        canonical: "L",
        aliases: &["L"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "help",
        aliases: &["h", "?", "help"],
        value_kind: OptionValueKind::Optional,
    },
    OptionSpec {
        canonical: "version",
        aliases: &["version"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "buildconf",
        aliases: &["buildconf"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "formats",
        aliases: &["formats"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "muxers",
        aliases: &["muxers"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "demuxers",
        aliases: &["demuxers"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "devices",
        aliases: &["devices"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "codecs",
        aliases: &["codecs"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "decoders",
        aliases: &["decoders"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "encoders",
        aliases: &["encoders"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "bsfs",
        aliases: &["bsfs"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "protocols",
        aliases: &["protocols"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "filters",
        aliases: &["filters"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "pix_fmts",
        aliases: &["pix_fmts"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "layouts",
        aliases: &["layouts"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "sample_fmts",
        aliases: &["sample_fmts"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "dispositions",
        aliases: &["dispositions"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "colors",
        aliases: &["colors"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "loglevel",
        aliases: &["loglevel", "v"],
        value_kind: OptionValueKind::Required,
    },
    OptionSpec {
        canonical: "report",
        aliases: &["report"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "max_alloc",
        aliases: &["max_alloc"],
        value_kind: OptionValueKind::Required,
    },
    OptionSpec {
        canonical: "cpuflags",
        aliases: &["cpuflags"],
        value_kind: OptionValueKind::Required,
    },
    OptionSpec {
        canonical: "cpucount",
        aliases: &["cpucount"],
        value_kind: OptionValueKind::Required,
    },
    OptionSpec {
        canonical: "hide_banner",
        aliases: &["hide_banner"],
        value_kind: OptionValueKind::Optional,
    },
    OptionSpec {
        canonical: "sources",
        aliases: &["sources"],
        value_kind: OptionValueKind::Required,
    },
    OptionSpec {
        canonical: "sinks",
        aliases: &["sinks"],
        value_kind: OptionValueKind::Required,
    },
    OptionSpec {
        canonical: "f",
        aliases: &["f"],
        value_kind: OptionValueKind::Required,
    },
    OptionSpec {
        canonical: "unit",
        aliases: &["unit"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "prefix",
        aliases: &["prefix"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "byte_binary_prefix",
        aliases: &["byte_binary_prefix"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "sexagesimal",
        aliases: &["sexagesimal"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "pretty",
        aliases: &["pretty"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "output_format",
        aliases: &["output_format", "print_format", "of"],
        value_kind: OptionValueKind::Required,
    },
    OptionSpec {
        canonical: "select_streams",
        aliases: &["select_streams"],
        value_kind: OptionValueKind::Required,
    },
    OptionSpec {
        canonical: "sections",
        aliases: &["sections"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "show_data",
        aliases: &["show_data"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "show_data_hash",
        aliases: &["show_data_hash"],
        value_kind: OptionValueKind::Optional,
    },
    OptionSpec {
        canonical: "show_error",
        aliases: &["show_error"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "show_format",
        aliases: &["show_format"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "show_frames",
        aliases: &["show_frames"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "show_entries",
        aliases: &["show_entries"],
        value_kind: OptionValueKind::Required,
    },
    OptionSpec {
        canonical: "show_log",
        aliases: &["show_log"],
        value_kind: OptionValueKind::Optional,
    },
    OptionSpec {
        canonical: "show_packets",
        aliases: &["show_packets"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "show_programs",
        aliases: &["show_programs"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "show_stream_groups",
        aliases: &["show_stream_groups"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "show_streams",
        aliases: &["show_streams"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "show_chapters",
        aliases: &["show_chapters"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "count_frames",
        aliases: &["count_frames"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "count_packets",
        aliases: &["count_packets"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "show_program_version",
        aliases: &["show_program_version"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "show_library_versions",
        aliases: &["show_library_versions"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "show_versions",
        aliases: &["show_versions"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "show_pixel_formats",
        aliases: &["show_pixel_formats"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "show_optional_fields",
        aliases: &["show_optional_fields"],
        value_kind: OptionValueKind::Optional,
    },
    OptionSpec {
        canonical: "show_private_data",
        aliases: &["show_private_data", "private"],
        value_kind: OptionValueKind::Optional,
    },
    OptionSpec {
        canonical: "bitexact",
        aliases: &["bitexact"],
        value_kind: OptionValueKind::None,
    },
    OptionSpec {
        canonical: "read_intervals",
        aliases: &["read_intervals"],
        value_kind: OptionValueKind::Required,
    },
    OptionSpec {
        canonical: "i",
        aliases: &["i"],
        value_kind: OptionValueKind::Required,
    },
    OptionSpec {
        canonical: "o",
        aliases: &["o"],
        value_kind: OptionValueKind::Required,
    },
    OptionSpec {
        canonical: "print_filename",
        aliases: &["print_filename"],
        value_kind: OptionValueKind::Required,
    },
    OptionSpec {
        canonical: "find_stream_info",
        aliases: &["find_stream_info"],
        value_kind: OptionValueKind::None,
    },
];

/// 兼容旧版 tao-probe 的隐藏别名映射.
pub const LEGACY_ALIAS_OPTIONS: &[(&str, &str, Option<&str>)] = &[
    // `--json` => `-of json`
    ("json", "output_format", Some("json")),
    // `--show-format` => `-show_format`
    ("show-format", "show_format", None),
    // `--show-streams` => `-show_streams`
    ("show-streams", "show_streams", None),
    // `--show-packets` => `-show_packets`
    ("show-packets", "show_packets", None),
    // `--quiet` => `-v error`
    ("quiet", "loglevel", Some("error")),
    // `-q` => `-v error`
    ("q", "loglevel", Some("error")),
];

/// 主选项帮助文本（对应 `ffprobe -h` 的 Main options 区段）.
pub const MAIN_OPTIONS_HELP_LINES: &[&str] = &[
    "-L                  show license",
    "-h <topic>          show help",
    "-? <topic>          show help",
    "-help <topic>       show help",
    "--help <topic>      show help",
    "-version            show version",
    "-buildconf          show build configuration",
    "-formats            show available formats",
    "-muxers             show available muxers",
    "-demuxers           show available demuxers",
    "-devices            show available devices",
    "-codecs             show available codecs",
    "-decoders           show available decoders",
    "-encoders           show available encoders",
    "-bsfs               show available bit stream filters",
    "-protocols          show available protocols",
    "-filters            show available filters",
    "-pix_fmts           show available pixel formats",
    "-layouts            show standard channel layouts",
    "-sample_fmts        show available audio sample formats",
    "-dispositions       show available stream dispositions",
    "-colors             show available color names",
    "-loglevel <loglevel>  set logging level",
    "-v <loglevel>       set logging level",
    "-report             generate a report",
    "-max_alloc <bytes>  set maximum size of a single allocated block",
    "-cpuflags <flags>   force specific cpu flags",
    "-cpucount <count>   force specific cpu count",
    "-hide_banner <hide_banner>  do not show program banner",
    "-sources <device>   list sources of the input device",
    "-sinks <device>     list sinks of the output device",
    "-f <format>         force format",
    "-unit               show unit of the displayed values",
    "-prefix             use SI prefixes for the displayed values",
    "-byte_binary_prefix  use binary prefixes for byte units",
    "-sexagesimal        use sexagesimal format HOURS:MM:SS.MICROSECONDS for time units",
    "-pretty             prettify the format of displayed values, make it more human readable",
    "-output_format <format>  set the output printing format (available formats are: default, compact, csv, flat, ini, json, xml)",
    "-print_format       alias for -output_format (deprecated)",
    "-of <format>        alias for -output_format",
    "-select_streams <stream_specifier>  select the specified streams",
    "-sections           print sections structure and section information, and exit",
    "-show_data          show packets data",
    "-show_data_hash     show packets data hash",
    "-show_error         show probing error",
    "-show_format        show format/container info",
    "-show_frames        show frames info",
    "-show_entries <entry_list>  show a set of specified entries",
    "-show_log           show log",
    "-show_packets       show packets info",
    "-show_programs      show programs info",
    "-show_stream_groups  show stream groups info",
    "-show_streams       show streams info",
    "-show_chapters      show chapters info",
    "-count_frames       count the number of frames per stream",
    "-count_packets      count the number of packets per stream",
    "-show_program_version  show ffprobe version",
    "-show_library_versions  show library versions",
    "-show_versions      show program and library versions",
    "-show_pixel_formats  show pixel format descriptions",
    "-show_optional_fields  show optional fields",
    "-show_private_data  show private data",
    "-private            same as show_private_data",
    "-bitexact           force bitexact output",
    "-read_intervals <read_intervals>  set read intervals",
    "-i <input_file>     read specified file",
    "-o <output_file>    write to specified output",
    "-print_filename <print_file>  override the printed input filename",
    "-find_stream_info   read and decode the streams to fill missing information with heuristics",
];

/// AVOptions 名称接口（由 `ffprobe 7.1.3` 输出提取）.
pub const AVOPTION_NAMES: &[&str] = &[
    "aa_fixed_key",
    "activation_bytes",
    "advanced_editlist",
    "alllayers",
    "allowed_extensions",
    "allowed_media_types",
    "allowed_segment_extensions",
    "analyzeduration",
    "angle",
    "apply_cropping",
    "apply_defdispwin",
    "apply_phase_inv",
    "apply_trc",
    "ar",
    "assetmaps",
    "async_depth",
    "audible_fixed_key",
    "audible_iv",
    "audible_key",
    "auth_type",
    "auto_convert",
    "avioflags",
    "bandwidth",
    "bit_rate",
    "bits_per_codeword",
    "blank_value",
    "block",
    "buffer_size",
    "bug",
    "ca_file",
    "cafile",
    "cc_format",
    "cenc_decryption_key",
    "cert_file",
    "ch_layout",
    "change_field_order",
    "channel",
    "channel_order",
    "channels",
    "chapter",
    "chapter_end",
    "chapter_start",
    "chars_per_frame",
    "chroma_sample_location",
    "code_size",
    "codec_whitelist",
    "color_primaries",
    "color_range",
    "color_trc",
    "colorspace",
    "compute_clut",
    "compute_edt",
    "compute_pcr",
    "connect",
    "connect_timeout",
    "connection_timeout",
    "cons_noisegen",
    "content_type",
    "cookies",
    "core_only",
    "correct_ts_overflow",
    "crop",
    "crtc_id",
    "cryptokey",
    "custom_stride",
    "data_field",
    "debug",
    "decryption_iv",
    "decryption_key",
    "default_delay",
    "default_fps",
    "deint",
    "device",
    "discard_damaged_percentage",
    "downmix",
    "draw_mouse",
    "drc_scale",
    "drop_second_field",
    "dscp",
    "dual_mono_mode",
    "dump_separator",
    "dumpgraph",
    "duration_probesize",
    "dvb_substream",
    "dvbuffer",
    "dvguid",
    "dvtype",
    "ec",
    "eia608_extract",
    "enable_drefs",
    "enable_er",
    "encryption",
    "end",
    "end_offset",
    "enforced_encryption",
    "err_detect",
    "exchange",
    "export_all",
    "export_path_metadata",
    "export_side_data",
    "export_xmp",
    "extension_picky",
    "extern_huff",
    "extra_bits_bug",
    "extra_hw_frames",
    "f_err_detect",
    "f_strict",
    "fdebug",
    "fflags",
    "ffrtmphttp_tls",
    "ffs",
    "field_order",
    "fifo_size",
    "filmgrain",
    "fix_teletext_pts",
    "flags",
    "flags2",
    "flv_full_metadata",
    "flv_ignore_prevtag",
    "flv_metadata",
    "follow",
    "follow_mouse",
    "forced_subs_only",
    "format",
    "format_modifier",
    "format_whitelist",
    "formatprobesize",
    "fpsprobesize",
    "fragment_size",
    "frame_rate",
    "frame_size",
    "framerate",
    "frames_per_packet",
    "framethreads",
    "ftp-anonymous-password",
    "ftp-password",
    "ftp-user",
    "gamma",
    "gateway",
    "gpu",
    "gpu_copy",
    "grab_x",
    "grab_y",
    "graph",
    "graph_file",
    "hca_highkey",
    "hca_lowkey",
    "hca_subkey",
    "headers",
    "heavy_compr",
    "height",
    "http_multiple",
    "http_persistent",
    "http_proxy",
    "http_seekable",
    "hwaccel_flags",
    "icy",
    "idct",
    "ifo_palette",
    "ignore_chapters",
    "ignore_editlist",
    "ignore_length",
    "ignore_loop",
    "indexmem",
    "initial_pause",
    "input_format",
    "inputbw",
    "interleaved_read",
    "iptos",
    "ipttl",
    "is_avc",
    "iv",
    "keep_ar",
    "keep_ass_markup",
    "key",
    "key_file",
    "kind",
    "kmpreannounce",
    "kmrefreshrate",
    "latency",
    "layer",
    "layout",
    "linespeed",
    "linger",
    "list_devices",
    "list_formats",
    "list_standards",
    "listen",
    "listen_timeout",
    "live",
    "live_start_index",
    "load_plugin",
    "load_plugins",
    "local_addr",
    "local_port",
    "local_rtcpport",
    "local_rtpport",
    "localaddr",
    "localport",
    "location",
    "log_level",
    "loop",
    "lossmaxttl",
    "lowres",
    "m3u8_hold_counters",
    "max_delay",
    "max_file_size",
    "max_fps",
    "max_frame_delay",
    "max_gif_delay",
    "max_packet_size",
    "max_pixels",
    "max_port",
    "max_probe_packets",
    "max_reload",
    "max_samples",
    "max_size",
    "max_streams",
    "max_stts_delta",
    "max_ts_probe",
    "maxbw",
    "menu",
    "menu_lu",
    "menu_vts",
    "merge_alpha",
    "merge_pmt_versions",
    "messageapi",
    "method",
    "min_delay",
    "min_port",
    "minversion",
    "missing_streams",
    "mode",
    "mss",
    "multiple_requests",
    "nakreport",
    "nal_length_size",
    "name",
    "no_resync_search",
    "non_pcm_mode",
    "noref_gray",
    "num_capture_buffers",
    "num_output_buffers",
    "offset",
    "oheadbw",
    "operating_point",
    "oppoint",
    "overrun_nonfatal",
    "page",
    "palette",
    "paranoia_mode",
    "part",
    "passphrase",
    "password",
    "pattern_type",
    "payload_size",
    "pbkeylen",
    "peerlatency",
    "pg",
    "pgc",
    "pixel_format",
    "pkt_size",
    "plane_id",
    "playlist",
    "post_data",
    "postfilter",
    "prefer_x_start",
    "preindex",
    "private_key",
    "probesize",
    "protocol_blacklist",
    "protocol_whitelist",
    "raw_packet_size",
    "rcvbuf",
    "rcvlatency",
    "read_ahead_limit",
    "real_time",
    "real_time_latency_msec",
    "reconnect",
    "reconnect_at_eof",
    "reconnect_delay_max",
    "reconnect_delay_total_max",
    "reconnect_max_retries",
    "reconnect_on_http_error",
    "reconnect_on_network_error",
    "reconnect_streamed",
    "recv_buffer_size",
    "referer",
    "region",
    "region_border",
    "reorder_queue_size",
    "request_sample_fmt",
    "resize",
    "respect_retry_after",
    "resync_size",
    "reuse",
    "reuse_socket",
    "rist_profile",
    "routing_key",
    "rtbufsize",
    "rtcp_port",
    "rtmp_app",
    "rtmp_buffer",
    "rtmp_conn",
    "rtmp_flashver",
    "rtmp_listen",
    "rtmp_live",
    "rtmp_pageurl",
    "rtmp_playpath",
    "rtmp_subscribe",
    "rtmp_swfhash",
    "rtmp_swfsize",
    "rtmp_swfurl",
    "rtmp_swfverify",
    "rtmp_tcurl",
    "rtp_flags",
    "rtsp_flags",
    "rtsp_transport",
    "rw_timeout",
    "safe",
    "sample_rate",
    "sample_size",
    "scan_all_pmts",
    "sdp_flags",
    "secret",
    "seek2any",
    "seek_streams_individually",
    "seekable",
    "seg_format_options",
    "seg_max_retry",
    "segment_time_metadata",
    "select_region",
    "send_buffer_size",
    "server",
    "short_seek_size",
    "show_region",
    "side_data_prefer_packet",
    "skip_alpha",
    "skip_bottom",
    "skip_cursor",
    "skip_estimate_duration_from_pts",
    "skip_frame",
    "skip_gray",
    "skip_idct",
    "skip_initial_bytes",
    "skip_loop_filter",
    "skip_top",
    "skip_unknown_pmt",
    "smoother",
    "sndbuf",
    "snddropdelay",
    "sources",
    "speed",
    "srt_streamid",
    "srtp_in_params",
    "srtp_in_suite",
    "standard",
    "start",
    "start_number",
    "start_number_range",
    "start_time",
    "stream_name",
    "streamid",
    "strict",
    "strict-displaywin",
    "strict_mime_boundary",
    "sub_charenc",
    "sub_charenc_mode",
    "sub_name",
    "subfps",
    "subimage",
    "subsong",
    "surfaces",
    "target_level",
    "tcp_mss",
    "tcp_nodelay",
    "thread_type",
    "threads",
    "thumbnail",
    "ticks_per_frame",
    "tilethreads",
    "timeout",
    "timestamps",
    "title",
    "tlpktdrop",
    "tls_verify",
    "top",
    "track_index",
    "trans_color",
    "transtype",
    "trim",
    "ts",
    "ts_from_file",
    "tsbpd",
    "tsbpddelay",
    "ttl",
    "txt_chop_spaces",
    "txt_chop_top",
    "txt_default_region",
    "txt_duration",
    "txt_format",
    "txt_left",
    "txt_opacity",
    "txt_page",
    "txt_top",
    "txt_transparent",
    "type",
    "udplite_coverage",
    "use_absolute_path",
    "use_buggy_lpc",
    "use_libv4l2",
    "use_mfra_for",
    "use_odml",
    "use_tfdt",
    "use_wallclock_as_timestamps",
    "user_agent",
    "usetoc",
    "verifyhost",
    "video_size",
    "view_ids",
    "view_ids_available",
    "view_pos_available",
    "wallclock",
    "width",
    "window_id",
    "write_to_source",
    "x",
    "x264_build",
    "y",
];

/// 按别名查找主参数规格.
pub fn find_main_option(alias: &str) -> Option<&'static OptionSpec> {
    MAIN_OPTIONS.iter().find(|spec| spec.matches(alias))
}

/// 判断是否为 AVOption 名称接口参数.
pub fn is_avoption_name(alias: &str) -> bool {
    AVOPTION_NAMES.binary_search(&alias).is_ok()
}
